### PR TITLE
Disable all logging

### PR DESCRIPTION
**Pull request by MilenaStaporek**
Added if condition - only if LoggingEnabled property is true allow to create comms log files.
If LoggingEnabled is set to FALSE - no log files will be created at all.

### CODE REVIEW

**Review by MarcFletcher — APPROVED** [review]
Many thanks for the contribution. I only removed the change in default logging state, to leave it disabled.

**Comment by MilenaStaporek** [comment]
When do you plan to create a new release with these changes applied?

**Comment by MilenaStaporek** [comment]
Hello @MarcFletcher, i would like to ask you - if there is a possibility to get an update of the library to have all merged things included? It would be great

**Comment by MarcFletcher** [comment]
Agreed. I tried reaching out to the contributor that originally raised the nuget but haven't had a response. As a next step I'll create a nuget account myself, and do the latest release there as soon as I get a free couple of hours. Most likely in March.

I would of course always welcome anyone else to do it if they beat me to it. Many thanks.

**Comment by MarcFletcher** [comment]
We have control of the nuget package now so you can expect an update shortly.

**Comment by MilenaStaporek** [comment]
Hello!

Any updates with that new version of NetworkComms.Net?

Milena

**Comment by MarcFletcher** [comment]
Thanks for checking in. NuGet access is all sorted so that's one less obstacle ;)

My VS setup has gotten a bit out of date and, not from a lack of trying, I've not managed to get everything building successfully locally yet. If you're successfully building from source it would help me accelerate this if you could please share your settings. 🙏

**Comment by MarcFletcher** [comment]
I'm considering getting rid of the old .net version builds and using something more 'recent' ;) Just to ensure this suits your use case can you please confirm with me that a release targeting .net framework 4.8.1 would be ok for you?

**Comment by MilenaStaporek** [comment]
Hello,

Unfortunately we have everything from 4.8 version. Would it be a big problem to use 4.8?

**Comment by MarcFletcher** [comment]
Yea, sounds good. I already have builds succeeding on 4.8. I'll see if I can do a nuget release for both .net framework 4.8 initially and then later we can look at also doing something for .net 8.

**Comment by MarcFletcher** [comment]
A pre-release package of 3.0.4 is now available on nuget if you'd like to confirm this works for you - https://www.nuget.org/packages/NetworkCommsDotNet/3.0.4-beta.

Sorry for the delay.

**Comment by MilenaStaporek** [comment]
Hello!
I just  updated that package and it is compatible with our project, so I can confirm – it works 😊

**Comment by MarcFletcher** [comment]
Thanks for the update. A full release of v3.0.4. is now also available.

**Pull request merged**
